# Dataset settings
dataset:
  name: Cityscapes
  root: ../../data/cityscapes
  num_workers: 8

# Model definitions
UNet:
  batch_size: 16
  epoch: 100
  criterion:
    name: CrossEntropyLoss
  optimizer:
    name: Adam
    lr: 0.001
    weight_decay: 0.00001
  scheduler:
    name: PolyLR
    max_iter: 55800
  augmentation:
    RandomCrop:
      size: !!python/tuple [769, 769]
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0
    RandomHorizontalFlip:
  pretrained_weights: weights/UNet_best_miou.pth

EAR_Net:
  batch_size: 8
  epoch: 100
  criterion:
    name: FocalLoss
    alpha: 1
    gamma: 1
  optimizer:
    name: AdamW
    lr: 0.001
  scheduler:
    name: PolyLR
    max_iter: 37200
  augmentation:
    RandomCrop:
      size: !!python/tuple [1024, 512]
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0
    RandomHorizontalFlip:
  pretrained_weights: weights/EAR_Net_best_miou.pth

DeepLabV3plus:
  backbone: Xception
  output_stride: 16
  batch_size: 8
  epoch: 100
  criterion:
    name: CrossEntropyLoss
  optimizer:
    name: AdamW
    lr: 0.001
  scheduler:
    name: PolyLR
    max_iter: 37200
  augmentation:
    RandomCrop:
      size: !!python/tuple [769, 769]
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0
    RandomHorizontalFlip:
  pretrained_weights: weights/DeepLabV3plus_best_miou.pth

Proposed:
  backbone: Xception
  output_stride: 16
  batch_size: 8
  epoch: 100
  criterion:
    name: CrossEntropyLoss
  optimizer:
    name: AdamW
    lr: 0.001
  scheduler:
    name: PolyLR
    max_iter: 37200
  augmentation:
    RandomCrop:
      size: !!python/tuple [769, 769]
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0
    RandomHorizontalFlip:
  pretrained_weights: weights/Proposed_best_miou.pth
