# Dataset settings
dataset:
  name: Cityscapes
  root: ../../data/cityscapes
  num_workers: 8
  pin_memory: False
  normalize_mean: !!python/tuple [0.28689554, 0.32513303, 0.28389177]
  normalize_std: !!python/tuple [0.18696375, 0.19017339, 0.18720214]

# Model definitions
AR_UNet:
  batch_size: 4
  epoch: 100
  criterion:
    name: FocalLoss
    alpha: 1
    gamma: 1
  optimizer:
    name: AdamW
    lr: 0.001
  scheduler:
    name: PolyLR
  augmentation:
    RandomResizedCrop:
      size: !!python/tuple [512, 1024]
      scale: auto
      ratio: auto
    GaussianBlur:
      kernel_size: 3
      sigma: !!python/tuple [0.1, 2.0]
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0
    RandomHorizontalFlip:
  pretrained_weights: weights/EAR_Net_best_miou.pth

Attention_DeepLabv3plus:
  backbone: Xception
  output_stride: 16
  batch_size: 8
  epoch: 100
  criterion:
    name: CrossEntropyLoss
  optimizer:
    name: AdamW
    lr: 0.001
  scheduler:
    name: PolyLR
  augmentation:
    RandomResizedCrop:
      size: !!python/tuple [769, 769]
      scale: auto
      ratio: auto
    GaussianBlur:
      kernel_size: 3
      sigma: !!python/tuple [0.1, 2.0]
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0
    RandomHorizontalFlip:
  pretrained_weights: weights/Attention_DeepLabv3plus_best_miou.pth

DeepLabv3plus:
  backbone: Xception
  output_stride: 16
  batch_size: 8
  epoch: 100
  criterion:
    name: CrossEntropyLoss
  optimizer:
    name: AdamW
    lr: 0.001
  scheduler:
    name: PolyLR
  augmentation:
    RandomResizedCrop:
      size: !!python/tuple [769, 769]
      scale: auto
      ratio: auto
    GaussianBlur:
      kernel_size: 3
      sigma: !!python/tuple [0.1, 2.0]
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0
    RandomHorizontalFlip:
  pretrained_weights: weights/DeepLabv3plus_best_miou.pth

EAR_Net:
  batch_size: 6
  epoch: 120
  criterion:
    name: FocalLoss
    alpha: 1
    gamma: 1
  optimizer:
    name: AdamW
    lr: 0.001
  scheduler:
    name: PolyLR
  augmentation:
    RandomResizedCrop:
      size: !!python/tuple [512, 1024]
      scale: auto
      ratio: auto
    GaussianBlur:
      kernel_size: 3
      sigma: !!python/tuple [0.1, 2.0]
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0
    RandomHorizontalFlip:
  pretrained_weights: weights/EAR_Net_best_miou.pth

UNet:
  batch_size: 8
  epoch: 100
  criterion:
    name: CrossEntropyLoss
  optimizer:
    name: AdamW
    lr: 0.001
  scheduler:
    name: PolyLR
  augmentation:
    RandomResizedCrop:
      size: !!python/tuple [512, 1024]
      scale: auto
      ratio: auto
    GaussianBlur:
      kernel_size: 3
      sigma: !!python/tuple [0.1, 2.0]
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0
    RandomHorizontalFlip:
  pretrained_weights: weights/UNet_best_miou.pth

Proposed:
  backbone: Xception
  output_stride: 16
  batch_size: 8
  epoch: 100
  criterion:
    name: CrossEntropyLoss
  optimizer:
    name: AdamW
    lr: 0.001
  scheduler:
    name: PolyLR
  augmentation:
    RandomResizedCrop:
      size: !!python/tuple [ 769, 769 ]
      scale: auto
      ratio: auto
    GaussianBlur:
      kernel_size: 3
      sigma: !!python/tuple [ 0.1, 2.0 ]
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0
    RandomHorizontalFlip:
  pretrained_weights: weights/Proposed_best_miou.pth
