# Dataset settings
dataset:
  name: Cityscapes
  root: ../../data/cityscapes
  num_workers: 8
  pin_memory: True
  normalize_mean: !!python/tuple [0.28689554, 0.32513303, 0.28389177]
  normalize_std: !!python/tuple [0.18696375, 0.19017339, 0.18720214]
  class_weight: !!python/tuple [0.8373, 0.918, 0.866, 1.0345, 1.0166, 0.9969, 0.9754, 1.0489, 0.8786, 1.0023,
                                0.9539, 0.9843, 1.1116, 0.9037, 1.0865, 1.0955, 1.0865, 1.1529, 1.0507]

# Model definitions
Attention_DeepLabv3plus:
  backbone: Xception
  output_stride: 16
  batch_size: 8
  epoch: 100
  criterion:
    name: CrossEntropyLoss
  optimizer:
    name: AdamW
    lr: 0.001
  scheduler:
    name: PolyLR
  augmentation:
    RandomCrop:
      size: !!python/tuple [769, 769]
    RandomAdjustSharpness:
      sharpness_factor: 2
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0
    RandomHorizontalFlip:
  pretrained_weights: weights/Attention_DeepLabv3plus_best_miou.pth

DeepLabv3plus:
  backbone: Xception
  output_stride: 16
  batch_size: 8
  epoch: 100
  criterion:
    name: CrossEntropyLoss
  optimizer:
    name: AdamW
    lr: 0.001
  scheduler:
    name: PolyLR
  augmentation:
    RandomCrop:
      size: !!python/tuple [769, 769]
    RandomAdjustSharpness:
      sharpness_factor: 2
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0
    RandomHorizontalFlip:
  pretrained_weights: weights/DeepLabv3plus_best_miou.pth

EAR_Net:
  batch_size: 6
  epoch: 120
  criterion:
    name: FocalLoss
    alpha: 1
    gamma: 1
  optimizer:
    name: AdamW
    lr: 0.001
  scheduler:
    name: PolyLR
  augmentation:
    RandomCrop:
      size: !!python/tuple [512, 1024]
    RandomAdjustSharpness:
      sharpness_factor: 2
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0
    RandomHorizontalFlip:
  pretrained_weights: weights/EAR_Net_best_miou.pth

UNet:
  batch_size: 8
  epoch: 100
  criterion:
    name: CrossEntropyLoss
  optimizer:
    name: AdamW
    lr: 0.001
  scheduler:
    name: PolyLR
  augmentation:
    RandomCrop:
      size: !!python/tuple [512, 1024]
    RandomAdjustSharpness:
      sharpness_factor: 2
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0
    RandomHorizontalFlip:
  pretrained_weights: weights/UNet_best_miou.pth

Proposed:
  batch_size: 8
  epoch: 110
  criterion:
    name: CrossEntropyLoss
  aux_criterion:
    name: CrossEntropyLoss
  aux_factor: !!python/tuple [0.2, 0.5]
  optimizer:
    name: RAdam
    lr: 0.001
    weight_decay: 0
  scheduler:
    name: PolyLR
  augmentation:
    RandomResize:
      min_scale: 0.75
      max_scale: 2.0
    RandomCrop:
      size: !!python/tuple [512, 1024]
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0
    RandomHorizontalFlip:
  pretrained_weights: weights/Proposed_best_miou.pth

GCMNet:
  backbone: Xception
  output_stride: 16
  batch_size: 8
  epoch: 100
  criterion:
    name: FocalLoss
    alpha: 1
    gamma: 1
  optimizer:
    name: AdamW
    lr: 0.0001
  scheduler:
    name: PolyLR
  augmentation:
    RandomCrop:
      size: !!python/tuple [512, 1024]
    RandomAdjustSharpness:
      sharpness_factor: 2
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0
    RandomHorizontalFlip:
  pretrained_weights: weights/GCMNet_best_miou.pth

PSPNet:
  backbone: ResNet101
  output_stride: 16
  batch_size: 8
  epoch: 100
  criterion:
    name: CrossEntropyLoss
  optimizer:
    name: AdamW
    lr: 0.0001
  scheduler:
    name: PolyLR
  augmentation:
    RandomCrop:
      size: !!python/tuple [512, 1024]
    RandomAdjustSharpness:
      sharpness_factor: 2
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0
    RandomHorizontalFlip:
  pretrained_weights: weights/PSPNet_best_miou.pth
