# Dataset settings
dataset:
  name: Cityscapes
  root: ../../data/cityscapes
  image_size: 1024x2048
  ignore_index: 255
  num_workers: 8

# Model settings
model:
  name: DeepLabV3plus
  amp_enabled: True
  num_classes: 20

# Model definitions
UNet:
  batch_size: 16
  epoch: 100
  criterion:
    name: CrossEntropyLoss
  optimizer:
    name: Adam
    lr: 0.001
    weight_decay: 0.00001
  scheduler:
    name: ReduceLROnPlateau
    factor: 0.5
    patience: 5
    min_lr: 0.00005
  pretrained_weights: weights/UNet_best.pth

ResNet34:
  batch_size: 16
  epoch: 100
  criterion:
    name: CrossEntropyLoss
  optimizer:
    name: Adam
    lr: 0.001
    weight_decay: 0.00001
  scheduler:
    name: ReduceLROnPlateau
    factor: 0.5
    patience: 5
    min_lr: 0.00005
  pretrained_weights: weights/ResNet34_val_best.pth

AR_UNet:
  batch_size: 8
  epoch: 100
  criterion:
    name: CrossEntropyLoss
  optimizer:
    name: Adam
    lr: 0.0005
    weight_decay: 0.00001
  scheduler:
    name: ReduceLROnPlateau
    factor: 0.5
    patience: 5
    min_lr: 0.00005
  pretrained_weights: weights/Proposed_best.pth

DeepLabV3plus:
  batch_size: 8
  epoch: 31
  iter: 90000
  criterion:
    name: CrossEntropyLoss
  optimizer:
    name: Adam
    lr: 0.007
    weight_decay: 0.00001
  scheduler:
    name: WarmupPolyLR
  pretrained_weights: weights/DeepLabV3plus_best.pth
