dataset:
  image_size: 800x400
  num_classes: 20
  num_workers: 8
  root: ../../data/cityscapes

model: UNet
amp_enabled: True

UNet:
  batch_size: 16
  epoch: 100
  optimizer:
    name: Adam
    lr: 0.001
    weight_decay: 0.00001
  scheduler:
    name: ReduceLROnPlateau
    factor: 0.5
    patience: 5
    min_lr: 0.00005
  pretrained_weights: weights/UNet_best.pth

Backbone:
  batch_size: 16
  epoch: 100
  optimizer:
    name: Adam
    lr: 0.001
    weight_decay: 0.00001
  scheduler:
    name: ReduceLROnPlateau
    factor: 0.5
    patience: 5
    min_lr: 0.00005
  pretrained_weights: weights/Backbone_val_best.pth

Proposed:
  batch_size: 4
  epoch: 100
  optimizer:
    name: Adam
    lr: 0.001
    weight_decay: 0.00001
  scheduler:
    name: ReduceLROnPlateau
    factor: 0.5
    patience: 5
    min_lr: 0.00005
  pretrained_weights: weights/Proposed_best.pth
