# Dataset settings
dataset:
  image_size: 400x800
  num_classes: 20
  num_workers: 8
  root: ../../data/cityscapes

# Model settings
model: UNet
amp_enabled: True

# Model definitions
UNet:
  batch_size: 16
  epoch: 100
  optimizer:
    name: Adam
    lr: 0.001
    weight_decay: 0.00001
  scheduler:
    name: ReduceLROnPlateau
    factor: 0.5
    patience: 5
    min_lr: 0.00005
  pretrained_weights: weights/UNet_best.pth

ResNet34:
  batch_size: 16
  epoch: 100
  optimizer:
    name: Adam
    lr: 0.001
    weight_decay: 0.00001
  scheduler:
    name: ReduceLROnPlateau
    factor: 0.5
    patience: 5
    min_lr: 0.00005
  pretrained_weights: weights/Backbone_val_best.pth

AR_UNet:
  batch_size: 8
  epoch: 100
  optimizer:
    name: Adam
    lr: 0.0005
    weight_decay: 0.00001
  scheduler:
    name: ReduceLROnPlateau
    factor: 0.5
    patience: 5
    min_lr: 0.00005
  pretrained_weights: weights/Proposed_best.pth
